Replace references to irony-mode with ccls. Update config for ccls
ZachMassia/PlatformIO-Mode pull request #15
Opened 2021-04-09 18:12 UTC by dantecatalfamo

Fixes #14

2021-04-15 02:38 UTC, ZachMassia requested changes
Hey sorry for the delay! 

Thanks for the pull request. I unfortunately don't have the time to keep up with changes to Platformio these days. Glad it's still all working for the most part it seems.

If we could update that one comment to reflect the new completion package I'll go ahead and merge it.

Thanks!

2021-04-15 02:38 UTC, ZachMassia commented on README.md
>  ;; when needed (platformio.ini present in project root).
Hey if you could update the comment here I think it should all be good to go!

2021-04-15 15:46 UTC, dantecatalfamo commented on README.md
>  ;; when needed (platformio.ini present in project root).
Oops, nice catch!

2021-04-17 13:51 UTC, ZachMassia approved these changes

2021-04-17 13:51 UTC, merged